<!-- <script>
    function sum(num1, num2) {
        if (typeof num1 !== "number" || typeof num2 !== "number") {
            // return "你的参数不合法，请传递数字"

            // throw也是抛到函数的调用处
            throw "你的参数不合法，请传递数字"
        }
        return num1 + num2
    }

    console.log(sum(10, 20));
    console.log(sum("hello", 20));

    // 下面的代码不会执行
    console.log("我是后面的代码~");
</script> -->

<script>
    function sum(num1, num2) {
        if (typeof num1 !== "number" || typeof num2 !== "number") {
            // return "你的参数不合法，请传递数字"

            // throw也是抛到函数的调用处
            // 错误有很多类型，可以抛出一个指定类型的错误
            // throw new TypeError("你的参数不合法，请传递数字")
            throw new Error("你的参数不合法，请传递数字")
        }
        return num1 + num2
    }

    // 调用一个函数，有可能报错，有可能不报错
    // 把可能会报错的代码放到try中
    try {
        console.log(sum(10, 20));
        console.log(sum("hello", 20));
    } catch (err) {
        console.error(err);
    }


    // 下面的代码不会执行
    console.log("我是后面的代码~");
</script>