<!-- <script>
    // then的顺延   catch

    let promise = new Promise((resolve, reject) => {
        resolve("包包")
    })

    promise.then(res1=>{
        console.log("res1:",res1);
        return 666;
    },err=>{
        console.log("err1:",err);
    }).then(null,err=>{
        console.log("err2:",err);
    }).then(res3=>{
        // 不管是成功，还是失败，上一个then没有处理，就会顺延到下一个then中
        console.log("res3:",res3);
    })
</script> -->

<!-- <script>
    // then的顺延   catch

    let promise = new Promise((resolve, reject) => {
        resolve("包包")
    })

    promise.then(res1 => {
        console.log("res1:", res1);
        return 666;
    }, err => {
        console.log("err1:", err);
    }).then(null, err => {
        console.log("err2:", err);
    }).then(null, null)
        .then(null, null)
        .then(null, null)
        .then(null, null)
        .then(res3 => {
            console.log("res3:", res3);
        }, err3 => {
            console.log("err3:", err3);
        })
</script> -->

<!-- <script>
    // then的顺延   catch

    let promise = new Promise((resolve, reject) => {
        resolve("包包")
    })

    // promise.then(res1 => {
    //     console.log("res1:", res1);
    //     throw new Error("我是一个错误~")
    // }, err => {
    //     console.log("err1:", err);
    // }).then(res2=>{
    //     console.log("res2:",res2);
    // },null).then(null,err3=>{
    //     console.log("err3:",err3);
    // })

    promise.then(res1 => {
        console.log("res1:", res1);
        throw new Error("我是一个错误~")
    }, err => {
        console.log("err1:", err);
    }).then(res2 => {
        console.log("res2:", res2);
    }).catch(err3 => {
        console.log("err3:", err3);
    })
</script> -->

<script>
    let promise = new Promise((resolve, reject) => {
        // resolve("包包")
        reject("没钱")
    })

    promise.then(res => {
        console.log("res:", res);
    }).catch(err => {
        console.log("err:", err);
    })

</script>