<script>
    const promise = new Promise((resolve, reject) => {
        reject("bad")
    });
    promise.then(res => {
        console.log("res:", res);
    }, err => {
        console.log("err:", err);
        // throw new Error("我错了~")
    }).catch(err => {
        console.log("err:", err);
    }).finally(() => {
        console.log("不管成功还是失败都会执行~");
    })
</script>