<script>
    async function foo() {
        console.log("hello async函数~");

        // 1)返回普通值，promise是成功的promise
        // return 123;
        // return [1,2,3]

        // 2)异步函数自己返回了promise，得到的Promies状态由这个promise决定
        // return new Promise((resolve,reject)=>{
        //     // resolve("包包")
        //     reject("没钱")
        // })

        // 3）异步函数返回值是一个对象并且实现thenable，得到的Promies状态由then方法中做了什么才能决定
        // return {
        //     then(resolve, reject) {
        //         // resolve("包包")
        //         reject("没钱")
        //     }
        // }

        // 4）在async函数中抛出一个错误，得到的promise是一个失败的promsie
        throw new Error("我是一个错误~")
    }

    foo().then(res => {
        console.log("res:", res);
    }).catch(err => {
        console.log("err:", err);
    })
</script>